### ISSUE TITLE
How to work around using the colorpicker inside an alertdialog on a small phone (e.g. nexus5)

### ISSUE THREAD

**Issue by gizmomogwai** [mchome/flutter_colorpicker#1]
````
03-10 15:24:00.632  1140  1178 I flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
03-10 15:24:00.641  1140  1178 I flutter : The following message was thrown during layout:
03-10 15:24:00.641  1140  1178 I flutter : A RenderFlex overflowed by 43 pixels on the right.
03-10 15:24:00.671  1140  1178 I flutter : The overflowing RenderFlex has an orientation of Axis.horizontal.
03-10 15:24:00.671  1140  1178 I flutter : The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
03-10 15:24:00.671  1140  1178 I flutter : black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
03-10 15:24:00.671  1140  1178 I flutter : Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
03-10 15:24:00.671  1140  1178 I flutter : RenderFlex to fit within the available space instead of being sized to their natural size.
03-10 15:24:00.671  1140  1178 I flutter : This is considered an error condition because it indicates that there is content that cannot be
03-10 15:24:00.671  1140  1178 I flutter : seen. If the content is legitimately bigger than the available space, consider clipping it with a
03-10 15:24:00.671  1140  1178 I flutter : ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
03-10 15:24:00.671  1140  1178 I flutter : like a ListView.
03-10 15:24:00.671  1140  1178 I flutter : The specific RenderFlex in question is:
03-10 15:24:00.671  1140  1178 I flutter :   RenderFlex#0d25a relayoutBoundary=up1 OVERFLOWING
03-10 15:24:00.671  1140  1178 I flutter :   creator: Row ← Column ← ConstrainedBox ← Container ← ColorPicker ← _SingleChildViewport ←
03-10 15:24:00.671  1140  1178 I flutter :   _ScrollableScope ← IgnorePointer-[GlobalKey#66b26] ← Semantics ← Listener ← _GestureSemantics ←
03-10 15:24:00.671  1140  1178 I flutter :   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#cd00a] ← ⋯
03-10 15:24:00.671  1140  1178 I flutter :   parentData: offset=Offset(0.0, 271.0); flex=null; fit=null (can use size)
03-10 15:24:00.671  1140  1178 I flutter :   constraints: BoxConstraints(0.0<=w<=232.0, 0.0<=h<=Infinity)
03-10 15:24:00.671  1140  1178 I flutter :   size: Size(232.0, 78.0)
03-10 15:24:00.671  1140  1178 I flutter :   direction: horizontal
03-10 15:24:00.671  1140  1178 I flutter :   mainAxisAlignment: center
03-10 15:24:00.671  1140  1178 I flutter :   mainAxisSize: max
03-10 15:24:00.671  1140  1178 I flutter :   crossAxisAlignment: center
03-10 15:24:00.671  1140  1178 I flutter :   textDirection: ltr
03-10 15:24:00.672  1140  1178 I flutter :   verticalDirection: down
03-10 15:24:00.672  1140  1178 I flutter : ◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤◢◤
03-10 15:24:00.672  1140  1178 I flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
````

**Comment by mchome** [comment]
It should work in new version :)

**Comment by gizmomogwai** [comment]
looks better now on nexus5x, but nexus5 still has problems for you.
i am working with version 0.0.2 now, you might also want to tag the github repository :)

nexus5x screenshot
![screen](https://user-images.githubusercontent.com/165273/37245989-5854666a-24a1-11e8-9a84-f0ac5e4a7a98.png)

nexus5 screenshot:
![screen_nexus5](https://user-images.githubusercontent.com/165273/37246525-c1c3d23a-24aa-11e8-9122-57da255f596d.png)

**Comment by mchome** [comment]
It should work better in new version :)

**Comment by gizmomogwai** [comment]
Thanks a lot ... that are the fastest github answers I got like ever :)
Just a question in general (because I am new to flutter and its layouts):
Is it possible, to make the colorthing as wide as possible and adjust the height accordingly, to always get a square color area?

**Comment by mchome** [comment]
Oh, i add some parameters like `colorPickerWidth` and `colorPainterHeight` in the latest version. You can use them to control the widget width and color area height.
If you like to get a square color area in `AlertDialog`, i can add a parameter to achieve it:)

**Comment by gizmomogwai** [comment]
i saw that ... the question is, if it would be possible with flutter to auto adjust the width (until a nice maximum) and automatically make the height the same.

**Comment by mchome** [comment]
![low resolution](https://user-images.githubusercontent.com/7392658/37264736-258c301a-25ea-11e8-88c7-2dfc540c54d9.png)
_this is 720p device_

![high resolution](https://user-images.githubusercontent.com/7392658/37264743-2c0e16f6-25ea-11e8-8079-07aa761076de.png)
_this is 2k device_

![tablet](https://user-images.githubusercontent.com/7392658/37264847-bad5dc52-25ea-11e8-8e61-3c89b44c4405.png)
_and a tablet_

Is it you want?

**Comment by gizmomogwai** [comment]
wow .. this looks really good ... i think this makes sense....
the only thing that i could imagine is, that for a really big tablet or something in landscape mode, one might want to be able to specify a maximum size ... because if its filling the whole screen this might be too much :)

**Comment by mchome** [comment]
In new version, you can use `pickerAreaHeightPercent` to control the ratio on the picker area, default value is 1.0(square).
The orientation value generated by `Orientation orientation = MediaQuery.of(context).orientation;`, so it is convenient to change the widget width depending on orientation :)

**Comment by gizmomogwai** [comment]
I tested on my two real devices and it looks really good ... sorry for bothering you so long, and thank you very much!
