### ISSUE TITLE
Bug: ipad/iphone

### ISSUE THREAD

**Issue by sarp86** [mchome/flutter_colorpicker#104]
On ipad or iphone - for me colorpicker not works correctly. The rectangle is black or white but not display selected color. When I move my finger over the rectangle, the display shows white or black. The sliders next to it work and show the correct colour, but not in the large rectangle

https://github.com/mchome/flutter_colorpicker/assets/44084914/21d5c39f-0ccb-489b-9969-f2fe98a7f8fd

**Comment by Jo-Re** [comment]
@sarp86 I have the same problem too. This problem occurs since the last Flutter sdk updates, I switched back to 3.16.9 and it worked for me.

The repo should be adapted to the latest flutter sdk

**Comment by luciano-cervantes** [comment]
same problem here

**Comment by luciano-cervantes** [comment]
@sarp86 and @Jo-Re 

I made the correction and opened the PR.

https://github.com/mchome/flutter_colorpicker/pull/106
