### ISSUE TITLE
Error: The getter 'bodyText1' isn't defined for the class 'TextTheme'.  EDIT: Master needs to get pushed to pub.dev?

### ISSUE THREAD

**Issue by mark8044** [mchome/flutter_colorpicker#105]
This appears with newer master branch 3.22.x version of flutter

EDIT: This might be fixed in the files already merged in master branch, but the latest master isn't actually pushed to pub.dev so that when this is used as a dependency its on an older version

**Comment by evgfilim1** [comment]
The current master branch should definitely be pushed to pub.dev because it will break apps depending on this library. Flutter 3.22 was released to beta channel, deprecated `bodyText1` and `bodyText2` properties from `TextTheme` class were removed, so it doesn't compile.

For future readers: workaround in your `pubspec.yaml`:
```diff
-   flutter_colorpicker: ^1.0.3
+   flutter_colorpicker:
+     git:
+       url: https://github.com/mchome/flutter_colorpicker
+       ref: master  # or 786d04363f587b818ce585d25b9c2bb62de95aba
```

**Comment by adebola-duf** [comment]
@evgfilim1 Thank you so much. It really helped.

**Comment by mqaa** [comment]
I'm using the package flutter_quill (https://github.com/singerdmx/flutter-quill/issues/1865) that uses this package and building my app fails because of this issue. Any change the changes can be pushed to pub.dev?

**Comment by phubner** [comment]
Same issue here. Thanks for the workaround @evgfilim1

**Comment by ledjoncili** [comment]
Same issue. Please publish to pub.dev master branch

**Comment by KimFromMarietta** [comment]
Same issue, except that the problem occurs because my app depends on dashbook, which depends on flutter_colorpicker.  Currently, my app is crashing with flutter 3.22 due to the bodyText1 and bodyText2 deprecated fields

**Comment by mchome** [comment]
Updated.
