### ISSUE TITLE
Have the possibility to input a List<Color> to CircleColorPicker

### ISSUE THREAD

**Issue by silversquall** [mchome/flutter_colorpicker#12]
currently the List of colors is predefined to : 

  static const List<Color> colors = [
    Color(0xffff0000),
    Color(0xffffff00),
    Color(0xff00ff00),
    Color(0xff00ffff),
    Color(0xff0000ff),
    Color(0xffff00ff),
    Color(0xffff0000)
  ];

I'd like to have the possibility to input my own color list to :
  CircleColorPicker(
      {Key key,
      this.radius = 120,
      this.initialColor = const Color(0xffff0000),
      this.thumbColor = Colors.black,
      this.thumbRadius = 8,

thank you !

**Comment by mchome** [comment]
This package do not have CircleColorPicker, I don't understand the question.
