### ISSUE TITLE
Change default text color

### ISSUE THREAD

**Issue by tolstenko** [mchome/flutter_colorpicker#14]
How can I change the label color? I need to change the RGB text, dropdown and numbers.

![Screenshot from 2019-11-06 14-12-57](https://user-images.githubusercontent.com/2386417/68321040-c6015e80-009f-11ea-8476-4f0a1aae4ec6.png)
![Screenshot from 2019-11-06 14-14-09](https://user-images.githubusercontent.com/2386417/68321042-c699f500-009f-11ea-8967-3b04e0b6aeca.png)

**Comment by mchome** [comment]
You can change the text color by wrapping picker in to `Theme` widget and change the `textTheme`.
ref: https://flutter.dev/docs/cookbook/design/themes#creating-unique-themedata
