### ISSUE TITLE
Is it possible to give values in _colorTypes:

### ISSUE THREAD

**Issue by shiyiya** [mchome/flutter_colorpicker#16]
## Is it possible to give values in _colorTypes:
```
typedef ValueChanged <K, T> = void Function (K v, T value);
```
## why?

Can be used to set the theme `primarySwatch`

## 是否可以给_colorTypes内的值:

typedef ValueChanged<K,T> = void Function(K v,T value);

## why?

可用于设置主题 `primarySwatch`
```
 ThemeData(
      primarySwatch: $___$
      );
```

**Comment by mchome** [comment]
Can you extend your issue? What are you going to achieve?

**Comment by mchome** [comment]
https://github.com/mchome/flutter_colorpicker/blob/372e1e2863604a24160413caf897790b576929bd/lib/material_picker.dart#L25-L46
