### ISSUE TITLE
Landscape version?

### ISSUE THREAD

**Issue by codegrue** [mchome/flutter_colorpicker#2]
Would love an alternate layout that works in landscape format. Perhaps with the color square in the left and the sliders on the right. For reference see the date_picker.dart showDatePicker() dialog that displays differently depending on orientation.

**Comment by mchome** [comment]
![flutter_01](https://user-images.githubusercontent.com/7392658/44334659-bd296a80-a4a4-11e8-9716-815be4d40e99.png)
Like this?

**Comment by codegrue** [comment]
Perfect. Thanks!

Only other enhancement I would love is to be able to inject style into the title for both orientations. Trying to make it consistent with the built in material pickers and they have a background on the title.

**Comment by mchome** [comment]
![image](https://user-images.githubusercontent.com/7392658/44338635-14353c80-a4b1-11e8-87fe-80317d25b82f.png)
Something like this?
```dart
showDialog(
  context: context,
  builder: (BuildContext context) {
    return AlertDialog(
      titlePadding: EdgeInsets.all(0.0),
      contentPadding: EdgeInsets.all(0.0),
      title: Container(
        color: Theme.of(context).primaryColor,
        child: Center(
          child: const Text(
            'Pick a color!',
            style: TextStyle(
              fontSize: 20.0,
              color: const Color(0xffffffff),
            ),
          ),
        ),
        padding: EdgeInsets.all(20.0),
      ),
      content: SingleChildScrollView(
        child: ColorPicker(
          pickerColor: pickerColor,
          onColorChanged: changeColor,
          colorPickerWidth: 1000.0,
          pickerAreaHeightPercent: 0.7,
        ),
      ),
      actions: <Widget>[
        FlatButton(
          child: Text('Got it'),
          onPressed: () {
            setState(() => currentColor = pickerColor);
            Navigator.of(context).pop();
          },
        ),
      ],
    );
  },
)
```

**Comment by codegrue** [comment]
That is very nice! Only additional tweak for consistency with stock pickers would be the buttons should be "CANCEL" and "OK".

**Comment by mchome** [comment]
You can do this by editing the `AlertDialog`'s actions look like this.
```dart
actions: <Widget>[
  FlatButton(
    child: Text('OK'),
      onPressed: () {
        setState(() => currentColor = pickerColor);
        Navigator.of(context).pop();
    },
  ),
  FlatButton(
    child: Text('CANCEL'),
      onPressed: () => Navigator.of(context).pop(),
  ),
],
```

**Comment by codegrue** [comment]
Suggestion to update your project example to show usage of landscape orientation (and switching).

**Comment by codegrue** [comment]
This is what I get trying to package it into landscape:

![image](https://user-images.githubusercontent.com/2914616/44366616-38861e80-a49b-11e8-8f91-a552bfbbaccf.png)

**Comment by codegrue** [comment]
`colorPickerWidth: 1000.0 `fixed it. Thank you.
