### ISSUE TITLE
Manual Hex Input

### ISSUE THREAD

**Issue by jaxnz** [mchome/flutter_colorpicker#31]
Would it be a possibility to add the ability to type a Hex color in?

**Comment by slavap** [comment]
This feature could be very useful, please add it.

**Comment by msachner** [comment]
This would be very helpful, please add this feature.

**Comment by Legolaszstudio** [comment]
+1 for this feature, it already seems to be in a to-do phase. 
https://github.com/mchome/flutter_colorpicker/blob/d149012d43b0e8478809ab3fd306660b188251b5/lib/src/hsv_picker.dart#L352

So looking forward impatiently to it,
Happy developing!

**Comment by Techno-Disaster** [comment]
@mchome any update on this? :P
