### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by lig** [mchome/flutter_colorpicker#35]
I'm going to submit a PR for the null safety support.

It is a common practice to keep such a code in a separate branch, i.e. null-safety, to be able to support the main release in legacy mode whilst the null safety compatible release could be released from its branch.

Please, prepare the branch for null safety support PR.

**Comment by lig** [comment]
@mchome I see, you've merged #36 PR. It wasn't my intent to get it merged into master but I can live with that. So, no new code goes into legacy releases then. That is a way to do it.
Are you going to release a new package version having "nullsafety" in suffix? This will help migrating other depending packages to null safety.

**Comment by Abhi011999** [comment]
Yeah, it will be very helpful for the packages that are depending on this

**Comment by lig** [comment]
@mchome I would be happy to discuss how we can go forward from here.

**Comment by lig** [comment]
@mchome I wouldn't mind organizing the code into a proper `null-safety` branch and making it ready for a null safety ready pre-release version if you give me the access. I have no intentions of taking over the project but I can help with the maintenance.

**Comment by mchome** [comment]
Done.

**Comment by lig** [comment]
@mchome thank you so much!
