### ISSUE TITLE
How do you rotate the material picker

### ISSUE THREAD

**Issue by pradt** [mchome/flutter_colorpicker#39]
I'm assuming the example showed at https://user-images.githubusercontent.com/7392658/46619112-dde07900-cb53-11e8-91d9-a4d1ee70cf3b.png is the material picker. 

When I've added it to my app it shows up with a vertical layout, how do I change it to horizontal ? Do I need to rotate the widget ? 

Also - it would be good if example had comments to state which example it is showing (according to the images)

**Comment by mchome** [comment]
Rotate the phone.
