### ISSUE TITLE
Error after installing v0.5.0

### ISSUE THREAD

**Issue by samiraj99** [mchome/flutter_colorpicker#49]
`../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43: Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 'DragGestureRecognizer.addAllowedPointer'.
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../flutter/packages/flutter/lib/src/gestures/events.dart').
Change to a supertype of 'PointerEvent', or, for a covariant parameter, a subtype.
  void addAllowedPointer(PointerDownEvent event) {
                                          ^

../../flutter/packages/flutter/lib/src/gestures/monodrag.dart:256:8: Context: This is the overridden method ('addAllowedPointer').
  void addAllowedPointer(PointerEvent event) {
       ^
2

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sam/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1035

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command '/Users/sam/Documents/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
`

**Comment by jaumard** [comment]
Yep version 0.4.0 works fine, but with 0.5.0 I'm getting:

```
../../.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43: Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent', which does not match the corresponding type, 'PointerEvent', in the overridden method, 'DragGestureRecognizer.addAllowedPointer'.
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart' ('../../flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart' ('../../flutter/packages/flutter/lib/src/gestures/events.dart').
Change to a supertype of 'PointerEvent', or, for a covariant parameter, a subtype.
  void addAllowedPointer(PointerDownEvent event) {
                                          ^
../../flutter/packages/flutter/lib/src/gestures/monodrag.dart:256:8: Context: This is the overridden method ('addAllowedPointer').
  void addAllowedPointer(PointerEvent event) {

```

**Comment by mchome** [comment]
If you are using stable channel of flutter, install v0.4.0 at the moment.

**Comment by jaumard** [comment]
Yes, I am. If the version is supposed to be for other channels you should consider using a different semantic version for those so we can know not to use it. Just my 2 cents for the future.

**Comment by alanmxll** [comment]
v0.4.0 works fine

**Comment by nstrelow** [comment]
I am using beta which is on 2.2.2, same error.

**Comment by sgehrman** [comment]
same issue, will try 0.4.0

**Comment by blue492** [comment]
Same error here in Flutter  Stable  2.2.2

**Comment by arasu33** [comment]
Same error after using 0.5.0

**Comment by alifarhanaf** [comment]
I also wasn't using color picker then i found that html editor enhanced depends upon color picker. 
By using html_editor_enhanced: ^2.2.0 instead of html_editor_enhanced: ^2.2.0+1-dev.1 worked for me. 
pairing with color_picker 0.4.0.

**Comment by tsinis** [comment]
Hey @samiraj99 and others!

You can use a `flutter_colorpicker` via git dependency:

```yaml
  flutter_colorpicker:
    git:
      url: git://github.com/mchome/flutter_colorpicker.git
```

Until the new version is published to pub.dev because the master channel now contains unpublished version 0.6.0 which should be backward compatible with all recent Flutter channels. So you will be fine on whatever channel you are (stable/beta/dev/master).

If it's enough for your needs — please consider closing the issue. Thanks!
