### ISSUE TITLE
Select color by code control

### ISSUE THREAD

**Issue by stoneLee81** [mchome/flutter_colorpicker#50]
I want to flexibly control the selected color block through the code. I made a small demo and hardcoded a color 【0xffFFB400】 that did not exist in _defaultColors.  When I selected the color. The expectation is that no color block will be selected, but when I click, it is still selected. The color block I clicked.
in debug mode, I found that _currColor value is 0xffFFB400, but widget is still select the wrong color block .

```
...
const List<Color> _defaultColors = [Color(0xfff44336),Color(0xffe91e63),Color(0xff9c27b0),Color(0xff673ab7),Color(0xff3f51b5),Color(0xff2196f3),Color(0xff03a9f4),Color(0xff00bcd4),Color(0xff009688),Color(0xff4caf50),Color(0xffcddc39),Color(0xffff9800)];
....
void changeColor(Color color) => setState(() => _currColor = Color(0xffFFB400));
...
SingleChildScrollView(child:BlockPicker(availableColors: _defaultColors, pickerColor: _currColor, onColorChanged: changeColor
```

**Comment by tsinis** [comment]
Hey @stoneLee81 !

I'm not sure it's an issue with a package. You can just update your code with a color check, something like:

```dart
 void changeColor(Color color) {
    if (_defaultColors.contains(color)) {
      setState(() => _currColor = color);
    } else {
      throw Exception('The selected color is not on the list!');
      // and handle it via try/catch on other side, or just show a snackbar, etc.
    }
  }
```

If it's enough for your needs — please consider closing the issue. Thanks!

**Comment by dowski** [comment]
I think what the OP was asking for is the ability to change the selected color in the picker from the outside.

Currently, there's no way to do that once the widget has been constructed. The selected color can only be changed by interaction with the widget's UI. In the example shared above, `_currColor` can only be used for setting the initial value of the picker. If it changes (based on reloading backing data or something) the picker doesn't pick up that change.
