### ISSUE TITLE
Target dart2js failed: Exception

### ISSUE THREAD

**Issue by InfinityCoder88** [mchome/flutter_colorpicker#51]
Target dart2js failed: Exception:                                       
../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-0.5.0/lib/src/hsv_picker.dart:730:43:
Error: The parameter 'event' of the method 'AlwaysWinPanGestureRecognizer.addAllowedPointer' has type 'PointerDownEvent',
which does not match the corresponding type, 'PointerEvent', in the overridden method,
'DragGestureRecognizer.addAllowedPointer'.
 - 'PointerDownEvent' is from 'package:flutter/src/gestures/events.dart'
 ('../../../flutter/packages/flutter/lib/src/gestures/events.dart').
 - 'PointerEvent' is from 'package:flutter/src/gestures/events.dart'
 ('../../../flutter/packages/flutter/lib/src/gestures/events.dart').
  void addAllowedPointer(PointerDownEvent event) {
                                          ^
../../../flutter/packages/flutter/lib/src/gestures/monodrag.dart:256:8:
Info: This is the overridden method ('addAllowedPointer').
  void addAllowedPointer(PointerEvent event) {
       ^
Error: Compilation failed.

**Comment by mchome** [comment]
Install v0.4.0.
