### ISSUE TITLE
How can i get Label Color 

### ISSUE THREAD

**Issue by sooryaraj** [mchome/flutter_colorpicker#53]
is there any way to get label color i got a foreground color problem.

**Comment by tsinis** [comment]
Hey @sooryaraj 

It's not very clear from the description, but are you talking about something like background color vs text color readability? For example black text on dark grey color? If it's a case — this package provides the `useWhiteForeground` function for that. Which returns `true` if the background color is dark (so you may use white/light foreground), and `false` if the background color is light (in that case you should use dark colors in the foreground instead). You can also provide your own bias as a parameter there, please see it in action (in the example) here:
https://github.com/mchome/flutter_colorpicker/blob/74d898eeabd0dae1e3df2fad805fed6db5cb8da6/example/lib/main.dart#L96-L98

 If it's enough for your needs — please consider closing the issue. Thanks!
