### ISSUE TITLE
LayoutBuilder type

### ISSUE THREAD

**Issue by thedude61636** [mchome/flutter_colorpicker#6]
https://github.com/mchome/flutter_colorpicker/blob/27829f01a0b1fe359c6488aba62fd5d7d8c593ef/lib/block_picker.dart#L32

in one of your classes BlockPicker you're using a type LayoutBuilder which is already defined in the flutter core widgets and will cause issues when using your library, please rename it to something else like BlockLayoutBuilder or something

**Comment by mchome** [comment]
Fixed in `0.2.1`.
