### ISSUE TITLE
Outline white Color[ For visibility in white dialogs]

### ISSUE THREAD

**Issue by nikhilbadyal** [mchome/flutter_colorpicker#68]
See the image for better understanding. 

Black color is outlined with some glitter ? So it's visible even with black colored dialog. [Image 1]
But if we turn the tables and make the dialog white. white is not visible any more. [Image 2]

So can you outlined the white color like you did with black color so it's visible to the user. 

![photo_2021-12-06_22-48-20](https://user-images.githubusercontent.com/59223300/144891688-f1ecad06-f019-4d0d-aa97-b0946bdc8c2f.jpg)
![photo_2021-12-06_22-48-16](https://user-images.githubusercontent.com/59223300/144891701-d7ce0d9f-1a0d-4592-95c9-2d3cd9ab93ac.jpg)

**Comment by mchome** [comment]
Try v1.0.3.
