### ISSUE TITLE
PR broke a nice feature. 

### ISSUE THREAD

**Issue by nikhilbadyal** [mchome/flutter_colorpicker#69]
This the current status of block picker.(Video 1)  As you can see when I change color on selecting new color. It doesn't show check mark on the newly selected color. ( Video recorded from the web page).

Luckily i had the old version of this package. And you can see how it used to work in older versions. (Video 2). Whenever i select new color. It shows i tick mark on that color. 

I compared both the version and find out that the above commit broke this feature. Particularly  this line 

[Link to commit](https://github.com/mchome/flutter_colorpicker/commit/9389d23d42cb7b67b39d3cb550f43c7fd9912ce9)

```
&& (widget.pickerColor.value == color.value),
```
Can you fix this ? 

 

https://user-images.githubusercontent.com/59223300/144895934-76207983-d134-4b95-b5e7-f5422b7791c9.mp4

 

https://user-images.githubusercontent.com/59223300/144896456-168516d8-99b3-4d99-8a93-b5943950026c.mp4

**Comment by nikhilbadyal** [comment]
This the current status of block picker.(Video 1)  As you can see when I change color on selecting new color. It doesn't show check mark on the newly selected color. ( Video recorded from the web page).

Luckily i had the old version of this package. And you can see how it used to work in older versions. (Video 2). Whenever i select new color. It shows i tick mark on that color. 

I compared both the version and find out that the above commit broke this feature. Particularly  this line 

```
&& (widget.pickerColor.value == color.value),
```
Can you fix this ? 


 

https://user-images.githubusercontent.com/59223300/144895934-76207983-d134-4b95-b5e7-f5422b7791c9.mp4

 

https://user-images.githubusercontent.com/59223300/144896456-168516d8-99b3-4d99-8a93-b5943950026c.mp4

**Comment by mchome** [comment]
Try v1.0.3.
