### ISSUE TITLE
showDialog in example code not working

### ISSUE THREAD

**Issue by fabioselau077** [mchome/flutter_colorpicker#72]
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-1.0.3/lib/src/palette.dart:1055:15: Error: No named parameter with the name 'label'.
              label: widget.embeddedText ? const Text('Hex') : null,
              ^^^^^
../../development/flutter/packages/flutter/lib/src/material/input_decorator.dart:2517:9: Context: Found this candidate, but the arguments don't match.
  const InputDecoration({

        ^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-1.0.3/lib/src/material_picker.dart:137:27: Error: No named parameter with the name 'dragDevices'.

**Comment by mchome** [comment]
flutter version?

**Comment by mchome** [comment]
Upgrade your flutter sdk version to 2.5 or up with flutter_colorpicker version 1.x.
