### ISSUE TITLE
whenever i add this library to the code i got this error

### ISSUE THREAD

**Issue by Yash-Hingu** [mchome/flutter_colorpicker#73]
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-1.0.3/lib/src/palette.dart:1055:15: Error: No named parameter with the name 'label'.
              label: widget.embeddedText ? const Text('Hex') : null,
              ^^^^^
../../snap/flutter/common/flutter/packages/flutter/lib/src/material/input_decorator.dart:2517:9: Context: Found this candidate, but the arguments don't match.
  const InputDecoration({
        ^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-1.0.3/lib/src/material_picker.dart:137:27: Error: No named parameter with the name 'dragDevices'.
                .copyWith(dragDevices: PointerDeviceKind.values.toSet()),
                          ^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_colorpicker-1.0.3/lib/src/material_picker.dart:200:23: Error: No named parameter with the name 'dragDevices'.
            .copyWith(dragDevices: PointerDeviceKind.values.toSet()),
                      ^^^^^^^^^^^

**Comment by mchome** [comment]
Upgrade your flutter sdk version to 2.5 or up.
