### ISSUE TITLE
Submit new pub version?

### ISSUE THREAD

**Issue by garv-shah** [mchome/flutter_colorpicker#83]
A new version on pub.dev hasn't been released in 7 months, is it possible to push an update @mchome?

**Comment by JosefWN** [comment]
Would be nice! Running from master to make things work in my app right now.

**Comment by deandreamatias** [comment]
@mchome If you want, can transfer this repo and the pub.dev owner to https://github.com/flutter-form-builder-ecosystem. After that, we invite you and us can give more support to this package :D
