### ISSUE TITLE
Breaks when font size on device is larger

### ISSUE THREAD

**Issue by droidery** [mchome/flutter_colorpicker#9]
This is how the widget looks normally:

<img width="314" alt="one" src="https://user-images.githubusercontent.com/34681083/58175234-0c762300-7ce3-11e9-9203-3972d58139e9.png">

This is what happens when the user sets the font size to larger (using https://support.apple.com/en-us/HT202828 or https://support.google.com/accessibility/android/answer/6006972?hl=en).

<img width="304" alt="two" src="https://user-images.githubusercontent.com/34681083/58175239-0ed87d00-7ce3-11e9-9bcf-df9169755931.png">

The color text gets cut off.

**Comment by mchome** [comment]
Try commit `8d019e92ba9227640a5aa050f9f358ad339c3cb5`.

**Comment by droidery** [comment]
Thanks, that mostly fixes the problem. Only on the larger accessibility sizes does it overflow slightly.
